[CmdletBinding()]
param(
    [int]$BackendPort = 8001,
    [int]$FrontendPort = 5174,
    [ValidateSet("memory", "git")]
    [string]$RepositoryBackend = "memory",
    [string]$OpenPath = "/wiki",
    [switch]$EnableWebSocket,
    [switch]$NoOpen,
    [switch]$AllowPlaceholderLlm
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$LauncherDir = Split-Path -Parent $ScriptDir
$RepoRoot = Split-Path -Parent $LauncherDir
$BackendDir = Join-Path $RepoRoot "skillwiki"
$FrontendDir = Join-Path $RepoRoot "skillwiki-frontend"
$RuntimeDir = Join-Path $LauncherDir "runtime"
$LogDir = Join-Path $RuntimeDir "logs"
$PidFile = Join-Path $RuntimeDir "skillwiki-demo.pids.json"
$ConfigFile = Join-Path $LauncherDir "config.local.ps1"
$StopScript = Join-Path $ScriptDir "Stop-SkillWikiDemo.ps1"

New-Item -ItemType Directory -Force $LogDir | Out-Null

if (Test-Path $ConfigFile) {
    Write-Host "Loading local config: $ConfigFile"
    . $ConfigFile
}

if ($env:SKILLOS_DEMO_BACKEND_PORT) {
    $BackendPort = [int]$env:SKILLOS_DEMO_BACKEND_PORT
}
if ($env:SKILLOS_DEMO_FRONTEND_PORT) {
    $FrontendPort = [int]$env:SKILLOS_DEMO_FRONTEND_PORT
}
if ($env:SKILLOS_DEMO_REPOSITORY_BACKEND) {
    $RepositoryBackend = $env:SKILLOS_DEMO_REPOSITORY_BACKEND
}

if (-not (Test-Path $BackendDir)) {
    throw "Backend directory not found: $BackendDir"
}
if (-not (Test-Path $FrontendDir)) {
    throw "Frontend directory not found: $FrontendDir"
}

function ConvertFrom-SecureStringToPlainText([securestring]$SecureString) {
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureString)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
}

function Escape-SingleQuotedPowerShellString([string]$Value) {
    return $Value.Replace("'", "''")
}

function Test-PlaceholderValue([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $true
    }
    return $Value -match "demo-placeholder|replace-with|your-api-key|your-model-id|your_key"
}

function Read-RequiredText([string]$Prompt, [string]$DefaultValue = "") {
    while ($true) {
        if ([string]::IsNullOrWhiteSpace($DefaultValue)) {
            $value = Read-Host $Prompt
        } else {
            $value = Read-Host "$Prompt [$DefaultValue]"
            if ([string]::IsNullOrWhiteSpace($value)) {
                $value = $DefaultValue
            }
        }
        if (-not [string]::IsNullOrWhiteSpace($value)) {
            return $value.Trim()
        }
        Write-Host "This value is required."
    }
}

function Ensure-DeepSeekConfig {
    $allowPlaceholder = $AllowPlaceholderLlm -or ($env:SKILLOS_ALLOW_PLACEHOLDER_LLM -eq "1")
    $hasUsableConfig = `
        (-not (Test-PlaceholderValue $env:LLM_API_URL)) -and `
        (-not (Test-PlaceholderValue $env:LLM_MODEL)) -and `
        (-not (Test-PlaceholderValue $env:LLM_API_KEY))

    if ($hasUsableConfig) {
        Write-Host "LLM config loaded for model: $env:LLM_MODEL"
        return
    }

    if ($allowPlaceholder) {
        if (-not $env:LLM_API_URL) {
            $env:LLM_API_URL = "https://api.deepseek.com"
        }
        if (-not $env:LLM_MODEL) {
            $env:LLM_MODEL = "demo-placeholder-model"
        }
        if (-not $env:LLM_API_KEY) {
            $env:LLM_API_KEY = "demo-placeholder-key"
        }
        Write-Host "Using placeholder LLM values because placeholder mode is explicitly enabled."
        return
    }

    Write-Host ""
    Write-Host "DeepSeek API configuration is required for this SkillWiki demo."
    Write-Host "Values will be saved only to this local ignored file:"
    Write-Host "  $ConfigFile"
    Write-Host "Press Enter to accept the default URL/model, then paste your own API key when prompted."
    Write-Host ""

    $apiUrl = Read-RequiredText "DeepSeek API URL" "https://api.deepseek.com"
    $model = Read-RequiredText "DeepSeek model" "deepseek-v4-flash"
    while ($true) {
        $secureKey = Read-Host "DeepSeek API key (input hidden)" -AsSecureString
        $apiKey = ConvertFrom-SecureStringToPlainText $secureKey
        if (-not (Test-PlaceholderValue $apiKey)) {
            break
        }
        Write-Host "A real API key is required. The demo launcher will not continue with a placeholder key."
    }

    $configLines = @(
        "# Local SkillWiki demo configuration.",
        "# This file is generated by Start-SkillWikiDemo.ps1 and ignored by Git.",
        "# Do not commit or share this file.",
        "",
        "# Optional: set a Python executable with SkillWiki backend dependencies.",
        "# `$env:SKILLOS_PYTHON = 'C:\Path\To\python.exe'",
        "",
        ("`$env:LLM_API_URL = '" + (Escape-SingleQuotedPowerShellString $apiUrl) + "'"),
        ("`$env:LLM_MODEL = '" + (Escape-SingleQuotedPowerShellString $model) + "'"),
        ("`$env:LLM_API_KEY = '" + (Escape-SingleQuotedPowerShellString $apiKey) + "'"),
        "",
        "# Optional launch overrides:",
        "# `$env:SKILLOS_DEMO_REPOSITORY_BACKEND = 'memory'",
        "# `$env:SKILLOS_DEMO_BACKEND_PORT = '8001'",
        "# `$env:SKILLOS_DEMO_FRONTEND_PORT = '5174'"
    )
    $configLines | Set-Content -Encoding UTF8 $ConfigFile

    $env:LLM_API_URL = $apiUrl
    $env:LLM_MODEL = $model
    $env:LLM_API_KEY = $apiKey
    Write-Host ""
    Write-Host "DeepSeek config saved. Starting SkillWiki..."
    Write-Host ""
}

function Resolve-SkillWikiPython {
    $candidates = @()
    if ($env:SKILLOS_PYTHON) {
        $candidates += $env:SKILLOS_PYTHON
    }

    $repoVenv = Join-Path $BackendDir ".venv\Scripts\python.exe"
    $candidates += @($repoVenv, "C:\Python314\python.exe", "python")

    foreach ($candidate in $candidates) {
        try {
            $cmd = Get-Command $candidate -ErrorAction Stop
            $exe = $cmd.Source
            & $exe -c "import pydantic, fastapi, uvicorn" *> $null
            if ($LASTEXITCODE -eq 0) {
                return $exe
            }
        } catch {
        }
    }

    throw "No Python runtime with required SkillWiki backend dependencies was found. Set SKILLOS_PYTHON in skillwiki-one-click-launcher\config.local.ps1."
}

function Get-FreePort([int]$PreferredPort) {
    for ($offset = 0; $offset -lt 50; $offset++) {
        $port = $PreferredPort + $offset
        $busy = Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue
        if (-not $busy) {
            return $port
        }
    }
    throw "No free port found starting at $PreferredPort"
}

function Wait-HttpOk([string]$Url, [int]$TimeoutSeconds, [string]$Name) {
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        try {
            $resp = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 3
            if ($resp.StatusCode -ge 200 -and $resp.StatusCode -lt 500) {
                return
            }
        } catch {
            Start-Sleep -Seconds 1
        }
    }
    throw "$Name did not become ready: $Url"
}

if (Test-Path $StopScript) {
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $StopScript -Silent
}

$BackendPort = Get-FreePort $BackendPort
$FrontendPort = Get-FreePort $FrontendPort

Ensure-DeepSeekConfig

$PythonExe = Resolve-SkillWikiPython
$NpmExe = (Get-Command npm.cmd -ErrorAction Stop).Source
$Stamp = Get-Date -Format "yyyyMMdd-HHmmss"

$BackendOut = Join-Path $LogDir "backend-$Stamp.out.log"
$BackendErr = Join-Path $LogDir "backend-$Stamp.err.log"
$FrontendOut = Join-Path $LogDir "frontend-$Stamp.out.log"
$FrontendErr = Join-Path $LogDir "frontend-$Stamp.err.log"

$backendArgs = @(
    "-m", "skillwiki.api.main",
    "--host", "127.0.0.1",
    "--port", [string]$BackendPort,
    "--repository-backend", $RepositoryBackend
)

if ($RepositoryBackend -eq "git") {
    $SkillStorageDir = Join-Path $RuntimeDir "skill-storage-git"
    New-Item -ItemType Directory -Force $SkillStorageDir | Out-Null
    $backendArgs += @("--skill-storage-dir", $SkillStorageDir)
}

Write-Host "Starting SkillWiki backend on http://127.0.0.1:$BackendPort ..."
$backendProc = Start-Process `
    -FilePath $PythonExe `
    -ArgumentList $backendArgs `
    -WorkingDirectory $BackendDir `
    -RedirectStandardOutput $BackendOut `
    -RedirectStandardError $BackendErr `
    -WindowStyle Hidden `
    -PassThru

Wait-HttpOk "http://127.0.0.1:$BackendPort/health" 90 "Backend"

$env:SKILLOS_API_TARGET = "http://127.0.0.1:$BackendPort"
if ($EnableWebSocket) {
    Remove-Item Env:\VITE_SKILLOS_DISABLE_WS -ErrorAction SilentlyContinue
    $websocketDisabled = $false
} else {
    $env:VITE_SKILLOS_DISABLE_WS = "1"
    $websocketDisabled = $true
}

Write-Host "Starting SkillWiki frontend on http://127.0.0.1:$FrontendPort ..."
$frontendProc = Start-Process `
    -FilePath $NpmExe `
    -ArgumentList @("run", "dev", "--", "--host", "127.0.0.1", "--port", [string]$FrontendPort) `
    -WorkingDirectory $FrontendDir `
    -RedirectStandardOutput $FrontendOut `
    -RedirectStandardError $FrontendErr `
    -WindowStyle Hidden `
    -PassThru

Wait-HttpOk "http://127.0.0.1:$FrontendPort/" 60 "Frontend"
Wait-HttpOk "http://127.0.0.1:$FrontendPort/api/v1/skills?limit=1" 30 "Frontend proxy"

$fresh = Get-Date -Format "yyyyMMddHHmmss"
$sep = "?"
if ($OpenPath.Contains("?")) {
    $sep = "&"
}
$OpenUrl = ("http://127.0.0.1:{0}{1}{2}fresh={3}" -f $FrontendPort, $OpenPath, $sep, $fresh)

$status = [ordered]@{
    startedAt = (Get-Date).ToString("s")
    backendPid = $backendProc.Id
    frontendPid = $frontendProc.Id
    backendPort = $BackendPort
    frontendPort = $FrontendPort
    repositoryBackend = $RepositoryBackend
    websocketDisabled = $websocketDisabled
    frontendUrl = $OpenUrl
    apiTarget = $env:SKILLOS_API_TARGET
    logs = [ordered]@{
        backendOut = $BackendOut
        backendErr = $BackendErr
        frontendOut = $FrontendOut
        frontendErr = $FrontendErr
    }
}
$status | ConvertTo-Json -Depth 5 | Set-Content -Encoding UTF8 $PidFile

Write-Host ""
Write-Host "SkillWiki demo is running."
Write-Host "Frontend: $OpenUrl"
Write-Host "Backend:  http://127.0.0.1:$BackendPort"
Write-Host "PID file: $PidFile"
Write-Host "Logs:     $LogDir"
Write-Host ""

if (-not $NoOpen) {
    Start-Process $OpenUrl
}
